### ISSUE TITLE
Sidebar menu flashes in actual mobile device if sidebar does not have background image

### ISSUE THREAD

**Issue by jac0117** [creativetimofficial/material-dashboard-pro-angular#89] opened 2017-09-22 04:48 UTC
I removed the background image from the sidebar. Now whenever I expand a menu item with submenu item inside, the text in all menu items flashes three times. It only happens in a real mobile device. You don't have to fix this, I just want to know if you might know what is causing it. You can reproduce here:
http://dulobp1071cgr.cloudfront.net/

just signup with a bogus email, it'll create an account without having to confirm.

**Comment by alexandru-paduraru** [comment] 2017-09-26 08:16
@jac0117 thank you for the feedback. First of all, the first screen meme is awesome :-)) made my day. Second, I've tested and couldn't reproduce the sub-menus, do you have a test account?

![image-1](https://user-images.githubusercontent.com/2517758/30849760-1a83ead0-a2ac-11e7-8ecd-d635692163eb.jpg)

Best,
Alex

**Comment by jac0117** [comment] 2017-09-26 13:38
@alexandru-paduraru Thanks for the prompt reply. I had removed the submenu in order to avoid the flashing issue. I've added it back again. You can log in again to see the issue.

Thank you.

**Comment by alexandru-paduraru** [comment] 2017-09-27 10:12
@jac0117 yes, I can see it now. I will have a look with my colleague @dragosct10 and we will see what can cause that and come back with a solution.

**Comment by dragosct10** [comment] 2017-09-28 13:17
Hi, @jac0117! We checked on our product and the collapse is working fine for us. I will give you a 
link with video to see what happened on our product.

https://vimeo.com/235908248

Please, can you tell us if you added some classes or some properties or any modification that you made on the elements from the sidebar? 

Regards,
Dragos

**Comment by MSkraburski** [comment] 2017-12-01 09:13
Same thing happens for me. Sidebar on mobile devices does not work properly. I also removed background image but am currently facing two issues:
1. As stated above when I click on the sidebar using tablet e.g. iPad I got that red background image flashing a few times.
2. When I enter sidebar on smartphone I got different background color even though it is fixed by myself in css stylesheet.
Did you find a solution to at least one of that issues?

**Comment by MSkraburski** [comment] 2017-12-03 12:57
I solved the second issue but still face the first one mentioned by @jac0117 . Would be thankful for your response. Best regards

**Comment by jac0117** [comment] 2017-12-03 13:34
@MSkraburski - play around with the colors. I solved the issue, but I'm not quite sure how. I accidentally solved it when I decided to change the color scheme of my site.

**Comment by MSkraburski** [comment] 2017-12-07 14:43
Still did not find any solution. Where & which colors had you changed so that at the end you got it working properly @jac0117 ?

**Comment by MSkraburski** [comment] 2017-12-07 19:53
The most probable source of issue is admin-layout.component . I reduced the html code to: <div class="wrapper">
    <div class="sidebar" data-active-color="white" data-background-color="red" >
        <sidebar-cmp></sidebar-cmp>
    </div>
  <div class="main-panel">
        <navbar-cmp></navbar-cmp>
        <router-outlet></router-outlet>
        <div >
            <footer-cmp></footer-cmp>
        </div>
    </div>
</div>
It works well on all the devices but I still got that strange flashes on tablets. However, I found out that if I change `data-background-color="red"` to any other color or clear that line at all my sidebar crashes a lot. White lines disappeared and text got all grey instead of being white.

**Closed** 2018-01-16 13:59 UTC
Labels: bug
